title: "ZettelWiki"
description: "My Zettelkasten notes"
baseurl: "/zettelwiki" # The base URL path for your site
url: "https://tapangarg.github.io"
markdown: kramdown
theme: jekyll-theme-minimal

permalink: pretty
