title: "ZettelWiki"
description: "My Zettelkasten notes"
baseurl: "/zettelwiki" # The base URL path for your site
url: "https://tapangarg.github.io"
markdown: kramdown
remote_theme: pages-themes/dinky@v0.2.0
permalink: pretty

# Pagination settings
paginate: 100 # Number of items per page
paginate_path: "/page:num"
